name: inspector Compare test on Firefox
on:
  push:
    branches:
      - web-compairpage-test

jobs:
  project-run:
    name: Test inspector compare on Firefox browser
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run inspector Compare Test
        uses: cypress-io/github-action@v6
        with:
          working-directory: web-automation
          # 1. Add the browser flag to your custom command
          command: npm run test:inspector-compairPage-test -- --record --browser firefox
          # 2. Specify the browser for the GitHub Action
          browser: firefox
          record: true
        env:
          CYPRESS_RECORD_KEY: f84cd963-d926-4c10-af50-4863894cad86

      
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Inspector-Compare-Test-report
          path: web-automation/cypress/reports
          if-no-files-found: error 
