name: contractor MyEstimates test on Edge browser
on:
  push:
    branches:
      - web-myestimates-test 

jobs:
  project-run:
    name: Test contractor Myestimates on Edge browser
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Contractor Myestimates Test
        uses: cypress-io/github-action@v6
        with:
          working-directory: web-automation
          # 1. Add the browser flag to your custom command
          command: npm run test:contractor-myEstimates-test -- --record --browser edge
          # 2. Specify the browser for the GitHub Action
          browser: edge
          record: true
        env:
          CYPRESS_RECORD_KEY: f84cd963-d926-4c10-af50-4863894cad86

      
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Contractor-MyEstimates-Test-report
          path: web-automation/cypress/reports
          if-no-files-found: error 
